server:
  servlet:
    context-path: /uaa
  port: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  data:
    mongodb:
      host: auth-mongodb
      database: mb-trading-auth
      port: 27017