server:
  port: 5000
-------------
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
-------------
spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      database: mb-trading
      port: 27017

