server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health, turbine.stream
      base-path: /

spring:
  rabbitmq:
    host: rabbitmq

#turbine:
#  aggregator:
#    cluster-config: APPCLUSTER
#  app-config: trade-service
#  instanceUrlSuffix.APPCLUSTER: /hystrix.stream