server:
  port: 8092

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

security:
  oauth2:
    client:
      clientId: trade-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: http://localhost:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: serve

feign:
  hystrix:
    enabled: true

spring:
  data:
    mongodb:
      host: localhost
      database: mb-trading-trade
      port: 27017